services:
  db:
    image: postgres:17.5
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: AhuchaDigital-Postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: AhuchaDigital-API
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # Override DB host to point to the compose service
      DB_HOST: db
      # Optional: adjust API host used by the app if needed
      HOST_API: http://localhost:3000/api
    ports:
      - '3000:3000'
