version: '3'

services:
  db:
    image: postgres:17.5
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: AhuchaDigital-Postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
